/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.listacircular;

import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-30
 */
public class menu extends javax.swing.JFrame {

    ListaCircular objetoLista = new ListaCircular();

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listacircular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        PrimeroYUltimo = new javax.swing.JButton();
        agregarFinal = new javax.swing.JButton();
        addAfter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listacircular.setText("Crear Lista");
        listacircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listacircularActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor");

        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        PrimeroYUltimo.setText("Primero y Ultimo");
        PrimeroYUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeroYUltimoActionPerformed(evt);
            }
        });

        agregarFinal.setText("Crear Al Final");
        agregarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFinalActionPerformed(evt);
            }
        });

        addAfter.setText("Agregar despues de");
        addAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAfterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAfter)
                    .addComponent(agregarFinal)
                    .addComponent(PrimeroYUltimo)
                    .addComponent(listacircular)
                    .addComponent(consultar))
                .addGap(277, 277, 277))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listacircular))
                .addGap(18, 18, 18)
                .addComponent(consultar)
                .addGap(21, 21, 21)
                .addComponent(PrimeroYUltimo)
                .addGap(18, 18, 18)
                .addComponent(agregarFinal)
                .addGap(18, 18, 18)
                .addComponent(addAfter)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listacircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listacircularActionPerformed
        objetoLista.crearLista(Integer.parseInt(valor.getText()));
        valor.setText(""); // Limpia el campo automáticamente
    }//GEN-LAST:event_listacircularActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        objetoLista.consultar();
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarActionPerformed

    private void PrimeroYUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeroYUltimoActionPerformed
        objetoLista.mostrarPrimeroYUltimo();
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimeroYUltimoActionPerformed

    private void agregarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFinalActionPerformed
        objetoLista.AgregarAlFinal(Integer.parseInt(valor.getText())); 
        valor.setText("");
    }//GEN-LAST:event_agregarFinalActionPerformed

    private void addAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAfterActionPerformed
        String textoValor = valor.getText();
        if (textoValor == null || textoValor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Primero escribe el valor a insertar en el campo de texto.");
            return;
        }
        String valorDeseadoStr = JOptionPane.showInputDialog("¿Después de qué valor desea insertar el " + textoValor + "?"+"\nLista actual:\n" + objetoLista.mostrarLista());
        if (valorDeseadoStr != null && !valorDeseadoStr.isEmpty()) {
            objetoLista.AgregarDespuesDe(Integer.parseInt(textoValor), Integer.parseInt(valorDeseadoStr));
            valor.setText("");
            // Mostrar cómo quedaron los nodos
            JOptionPane.showMessageDialog(null, "Lista actual:\n" + objetoLista.mostrarLista());
        }
    }//GEN-LAST:event_addAfterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrimeroYUltimo;
    private javax.swing.JButton addAfter;
    private javax.swing.JButton agregarFinal;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listacircular;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
