/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.matrices;

import javax.swing.JOptionPane;

public class Pantalla extends javax.swing.JFrame {

    Matrices matris = new Matrices();

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        nombres = new javax.swing.JButton();
        totalVotos = new javax.swing.JButton();
        Ganador = new javax.swing.JButton();
        maxVosporMesa = new javax.swing.JButton();
        menosVotos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cantidad candidatos");

        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        f.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fKeyTyped(evt);
            }
        });

        jLabel2.setText("Numero de mesas");

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cKeyTyped(evt);
            }
        });

        crear.setText("Agregar resultados");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        consultar.setText("CONSULTAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        nombres.setText("Ingresar nombres");
        nombres.setEnabled(false);
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });
        nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresKeyTyped(evt);
            }
        });

        totalVotos.setText("Total Votos");
        totalVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVotosActionPerformed(evt);
            }
        });

        Ganador.setText("Candidato Ganador");
        Ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GanadorActionPerformed(evt);
            }
        });

        maxVosporMesa.setText("Max Votos Mesa");
        maxVosporMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxVosporMesaActionPerformed(evt);
            }
        });

        menosVotos.setText("Mesa con menos votos");
        menosVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosVotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(46, 46, 46)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(f, javax.swing.GroupLayout.DEFAULT_SIZE, 113,
                                                                Short.MAX_VALUE)
                                                        .addComponent(c))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nombres)
                                                .addGap(21, 21, 21))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(maxVosporMesa,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(totalVotos,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(crear,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                144, Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(Ganador,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(consultar,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addComponent(menosVotos))
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nombres)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crear)
                                        .addComponent(consultar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalVotos)
                                        .addComponent(Ganador))
                                .addGap(18, 18, 18)
                                .addComponent(maxVosporMesa)
                                .addGap(18, 18, 18)
                                .addComponent(menosVotos)
                                .addContainerGap(75, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menosVotosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menosVotosActionPerformed
        matris.mesaMenosVotos();
    }// GEN-LAST:event_menosVotosActionPerformed

    private void totalVotosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_totalVotosActionPerformed
        matris.sumaTotalVotos();
    }// GEN-LAST:event_totalVotosActionPerformed

    private void GanadorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GanadorActionPerformed
        matris.ganador();
        matris.ganadorMesaMax();

    }// GEN-LAST:event_GanadorActionPerformed

    private void maxVosporMesaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maxVosporMesaActionPerformed
        matris.mesaMaxVotos();

    }// GEN-LAST:event_maxVosporMesaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        matris.mesaMenosVotos();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fActionPerformed

    }// GEN-LAST:event_fActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearActionPerformed
        matris.crear(Integer.parseInt(f.getText()), Integer.parseInt(c.getText()));
    }// GEN-LAST:event_crearActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_consultarActionPerformed
        matris.consultar();
    }// GEN-LAST:event_consultarActionPerformed

    private void nombresKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_nombresKeyTyped
        // TODO add your handling code here:
    }// GEN-LAST:event_nombresKeyTyped

    private void fKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_fKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        } else {
            nombres.setEnabled(true);

        } // TODO add your handling code here:
    }// GEN-LAST:event_fKeyTyped

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombresActionPerformed
        
        matris.crearCandidatos(Integer.parseInt(f.getText()));

    }// GEN-LAST:event_nombresActionPerformed

    private void cKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        } // GEN-LAST:event_cKeyTyped
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String clave = JOptionPane.showInputDialog("Ingrese la contraseña:");
                if (clave.equals("1234")) {
                    new Pantalla().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ganador;
    private javax.swing.JTextField c;
    private javax.swing.JButton consultar;
    private javax.swing.JButton crear;
    private javax.swing.JTextField f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton maxVosporMesa;
    private javax.swing.JButton menosVotos;
    private javax.swing.JButton nombres;
    private javax.swing.JButton totalVotos;
    // End of variables declaration//GEN-END:variables
}
