/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoraplus;

/**
 *
 * @author URIEL MAURICIO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        Suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        divicion = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        porcentaje = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        borrarTodo = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        sen = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        log = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        jLabel1.setText("Primer Numero");

        jLabel2.setText("Segundo Numero");

        resultado.setText("Resultado");

        Suma.setText("+");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });

        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        divicion.setText("/");
        divicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divicionActionPerformed(evt);
            }
        });

        multiplicacion.setText("*");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });

        porcentaje.setText("%");
        porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeActionPerformed(evt);
            }
        });

        raiz.setText("Raiz");
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });

        borrarTodo.setText("C");
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });

        potencia.setText("Potencia");
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });

        sen.setText("sen");
        sen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senActionPerformed(evt);
            }
        });

        cos.setText("Cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        log.setText("Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(porcentaje)
                                .addGap(27, 27, 27)
                                .addComponent(raiz)
                                .addGap(18, 18, 18)
                                .addComponent(borrarTodo)
                                .addGap(30, 30, 30)
                                .addComponent(potencia))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Suma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resta)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                            .addComponent(a)
                                            .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(divicion)
                                        .addGap(46, 46, 46)
                                        .addComponent(multiplicacion))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cos)
                        .addGap(18, 18, 18)
                        .addComponent(log)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(resultado)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Suma)
                    .addComponent(resta)
                    .addComponent(divicion)
                    .addComponent(multiplicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentaje)
                    .addComponent(raiz)
                    .addComponent(borrarTodo)
                    .addComponent(potencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sen)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cos)
                        .addComponent(log)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senActionPerformed
           try {
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.calcularSen(numA, numB);
            resultado.setText("Resultado: " + res + " (sen(" + numA + " + " + numB + "))");
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese números válidos");
        }
    }//GEN-LAST:event_senActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.calcularCos(numA, numB);
            resultado.setText("Resultado: " + res + " (sen(" + numA + " + " + numB + "))");
    }//GEN-LAST:event_cosActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.calcularLog(numA, numB);
            resultado.setText("Resultado: " + res + " (Log(" + numA + " + " + numB + "))");
    }//GEN-LAST:event_logActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_raizActionPerformed
        try {
            double numA = Double.parseDouble(a.getText());
            if (numA < 0) {
                resultado.setText("Error: No se puede calcular raíz de número negativo");
            } else {
                double res = Operaciones.raizCuadrada(numA);
                resultado.setText("Resultado: " + res + " (√" + numA + ")");
            }
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese un número válido en el primer campo");
        }
    }// GEN-LAST:event_raizActionPerformed

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_borrarTodoActionPerformed
        a.setText("");
        b.setText("");
        resultado.setText("Resultado");
    }// GEN-LAST:event_borrarTodoActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_potenciaActionPerformed
        try {
            double numA = Double.parseDouble(a.getText());
            double res = Operaciones.potencia(numA);
            resultado.setText("Resultado: " + res + " (" + numA + "²)");
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese un número válido en el primer campo");
        }
    }// GEN-LAST:event_potenciaActionPerformed

   
    
    private void aActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_aActionPerformed

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SumaActionPerformed
        try {
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.suma(numA, numB);
            resultado.setText("Resultado: " + res);
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese números válidos");
        }
    }// GEN-LAST:event_SumaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_restaActionPerformed
        try {
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.resta(numA, numB);
            resultado.setText("Resultado: " + res);
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese números válidos");
        }
    }// GEN-LAST:event_restaActionPerformed

    private void divicionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_divicionActionPerformed
        try {
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.divicion(numA, numB);
            resultado.setText("Resultado: " + res);
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese números válidos");
        }
    }// GEN-LAST:event_divicionActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_multiplicacionActionPerformed
        try {
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.multiplicacion(numA, numB);
            resultado.setText("Resultado: " + res);
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese números válidos");
        }
    }// GEN-LAST:event_multiplicacionActionPerformed

    private void porcentajeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_porcentajeActionPerformed
        try {
            double numA = Double.parseDouble(a.getText());
            double numB = Double.parseDouble(b.getText());
            double res = Operaciones.porcentaje(numA, numB);
            resultado.setText("Resultado: " + res + " (" + numB + "% de " + numA + ")");
        } catch (NumberFormatException e) {
            resultado.setText("Error: Ingrese números válidos");
        }
    }// GEN-LAST:event_porcentajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Suma;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JButton borrarTodo;
    private javax.swing.JButton cos;
    private javax.swing.JButton divicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton log;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton porcentaje;
    private javax.swing.JButton potencia;
    private javax.swing.JButton raiz;
    private javax.swing.JButton resta;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton sen;
    // End of variables declaration//GEN-END:variables
}
