/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.waitingroom;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author URIEL MAURICIO
 */
public class MenuApp extends javax.swing.JFrame {

    private SistemaFila sistema;
    private javax.swing.Timer autoTimer;
    private boolean autoActivo = false;
    private int tickCount = 0;
    
    // Modelos para las listas
    private DefaultListModel<String> modeloFila = new DefaultListModel<>();
    private DefaultListModel<String> modeloCompras = new DefaultListModel<>();
    private DefaultListModel<String> modeloExpirados = new DefaultListModel<>();

    /**
     * Creates new form MenuApp
     */
    public MenuApp() {
        initComponents();
        
        sistema = new SistemaFila(30_000L); // TTL inicial de 30 seg
        
        // Poner los JList dentro de los JScrollPane que se arrastraron
        javax.swing.JList<String> jListaFila = new javax.swing.JList<>(modeloFila);
        listaFila.setViewportView(jListaFila);
        
        javax.swing.JList<String> jListaCompras = new javax.swing.JList<>(modeloCompras);
        listaCompras.setViewportView(jListaCompras);
        
        javax.swing.JList<String> jListaExpirados = new javax.swing.JList<>(modeloExpirados);
        listaExpirados.setViewportView(jListaExpirados);
         //aqui se inicia el timer osea que se va a ejecutar cada 1000 milisegundos pero se puede modificar con el lo que quiera
        autoTimer = new javax.swing.Timer(1000, e -> ejecutarTickAuto());
        
        autoTimer = new javax.swing.Timer(1000, e -> ejecutarTickAuto());
        
        btnAuto.addActionListener(e -> toggleAuto());
        
        spinTtl.setValue(30);
        spinTtl.addChangeListener(e -> {
            sistema.setTtlMs((int) spinTtl.getValue() * 1000L);
        });
        
        actualizarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaFila = new javax.swing.JScrollPane();
        listaCompras = new javax.swing.JScrollPane();
        listaExpirados = new javax.swing.JScrollPane();
        spinTtl = new javax.swing.JSpinner();
        btnAuto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnreiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAuto.setText("Auto-Simular");

        areaLog.setColumns(20);
        areaLog.setRows(5);
        jScrollPane1.setViewportView(areaLog);

        jLabel1.setText("Compraron");

        jLabel2.setText("Personas Activas");

        jLabel3.setText("Se les acado el tiempo");

        btnreiniciar.setText("reiniciar");
        btnreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(listaCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(btnAuto)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(listaExpirados, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(spinTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnreiniciar)
                        .addGap(72, 72, 72)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaExpirados, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnreiniciar)
                        .addGap(50, 50, 50)
                        .addComponent(spinTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btnAuto)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreiniciarActionPerformed
        accionReiniciar();
    }//GEN-LAST:event_btnreiniciarActionPerformed

    private void actualizarVista() {
        modeloFila.clear();
        for (NodoDoble n : sistema.getFilaPrincipal()) {
            String linea = "Usuario " + n.getIdUsuario() + " - " + n.getEstado() + " (" + Math.max(0, n.segundosRestantes()) + "s)";
            modeloFila.addElement(linea);
        }

        modeloCompras.clear();
        for (NodoDoble n : sistema.getComprasExitosas()) {
            modeloCompras.addElement("✔ Usuario " + n.getIdUsuario());
        }

        modeloExpirados.clear();
        for (NodoDoble n : sistema.getUsuariosExpirados()) {
            modeloExpirados.addElement("✗ Usuario " + n.getIdUsuario() + " - " + n.getEstado());
        }
    }

    private void log(String msg) {
        areaLog.append(msg + "\n");
        areaLog.setCaretPosition(areaLog.getDocument().getLength());
    }

    private void ejecutarTickAuto() {
        tickCount++;
        String res = sistema.ejecutarTick();
        log("[Tick #" + tickCount + "] " + res);
        actualizarVista();
    }
    
    private void toggleAuto() {
        autoActivo = !autoActivo;
        if (autoActivo) {
            autoTimer.start();
            btnAuto.setText("Detener");
            log("▶ Simulación automática iniciada (cada 1 s).");
        } else {
            autoTimer.stop();
            btnAuto.setText("Auto-Simular");
            log("⏹ Simulación detenida.");
        }
    }
    
    private void accionReiniciar() {
        int r = JOptionPane.showConfirmDialog(this,
            "¿Reiniciar todo el sistema?", "Confirmar",
            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (r == JOptionPane.YES_OPTION) {
            if (autoActivo) toggleAuto();
            sistema.reiniciar();
            tickCount = 0;
            areaLog.setText("");
            log("↺ Sistema reiniciado.");
            actualizarVista();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaLog;
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnreiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane listaCompras;
    private javax.swing.JScrollPane listaExpirados;
    private javax.swing.JScrollPane listaFila;
    private javax.swing.JSpinner spinTtl;
    // End of variables declaration//GEN-END:variables
}
